### ISSUE TITLE
404 Error on Building the UI image 

### ISSUE THREAD

**Issue by JacobSommerWolftech** [iptc/extra-ext#2]
Hello, 
I tried to follow the instructions to run this but go the following error at the end:

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/main/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/restricted/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/universe/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/main/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/restricted/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-updates/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/main/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/restricted/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/universe/source/Sources  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/restricted/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/wily-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.88.24 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'ui' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100

When I visited the webpage (http://archive.ubuntu.com/ubuntu/dists/wily/main/source/Sources)  it was also down. 

Is this project still active?

**Comment by bquinn** [comment]
Hi Jacob, thanks for getting in touch. I'll look into it more, but it looks like changing the ubuntu version in the first line of `ui/Dockerfile` from `FROM ubuntu:15.10` to `FROM ubuntu:18.04 ` should get the tool building.

If you're running locally, you could remove the .htpassword requirements by commenting out the Auth* lines in `ui/html/.htaccess`.

After docker compose has finished, and you've edited the .htaccess, you should be able to go to http://localhost:80/ and see the management screen appear.

Hope that helps!

**Comment by JacobSommerWolftech** [comment]
Yes! Thank you :) This helped a lot. I got it up and running now.

**Comment by bquinn** [comment]
Great, let us know if you have any other questions - now that I've fixed the repository to match the fix to this problem, I will close the issue.
